// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ennwofoqsblywberrjza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubndvZm9xc2JseXdiZXJyanphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDg0MTAsImV4cCI6MjA2NTY4NDQxMH0.IMyxXe1qNQgKBh7vDOOAp_GJ7MOdZckSwCx796HOv2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);